import type { Metadata } from 'next'
import { Anton, Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

const anton = Anton({
  subsets: ['latin'],
  variable: '--font-anton',
  weight: '400'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={`${inter.className} ${anton.variable} relative mx-auto max-w-screen-2xl`}
      >
        {children}
      </body>
    </html>
  )
}
